/* Copyright 2026 Gary Lobermier. Licensed under the Apache License, Version 2.0.
 *
 * Golden render: builds a small set list on disk, renders it through the real
 * load path, and hashes the result.
 *
 * The fixture stems are generated by an integer LCG and the set list contains
 * no click track, so the render path is copy/multiply/add only - no libm, no
 * platform-dependent transcendentals. That is what makes a byte-exact hash a
 * fair assertion on Linux, Windows and macOS alike rather than a source of
 * three-way disagreement.
 *
 * For the same reason the fixture uses 0 dB rather than a real gain: db_to_lin
 * goes through pow(), which is not guaranteed bit-identical between libms.
 * pow(10, 0) is exactly 1.0 everywhere. Gain scaling is covered with a
 * tolerance in test_engine, where that is the honest way to assert it.
 */
#include "bt_test.h"
#include "backtrack/bt_engine.h"
#include "backtrack/bt_wav.h"

#define SR 48000

/* Bump deliberately when the mixer is meant to change; never to make CI go
 * green. A surprise here means the audio changed. */
#define GOLDEN_HASH 0x9f275eafe9b7a0dfULL

static void write_stem(const char *path, uint32_t seed, int32_t ch, bt_frame n) {
    float *buf[2];
    for (int32_t c = 0; c < ch; c++)
        buf[c] = (float *)malloc((size_t)n * sizeof(float));
    bt_lcg_seed(seed);
    for (bt_frame i = 0; i < n; i++)
        for (int32_t c = 0; c < ch; c++) buf[c][i] = bt_lcg_sample();

    const float *p[2] = { buf[0], ch > 1 ? buf[1] : NULL };
    BT_CHECK_EQI(bt_wav_write_file(path, p, ch, SR, n), BT_OK);
    for (int32_t c = 0; c < ch; c++) free(buf[c]);
}

static void write_text(const char *path, const char *s) {
    FILE *f = fopen(path, "wb");
    BT_CHECK(f != NULL);
    if (!f) return;
    fwrite(s, 1, strlen(s), f);
    fclose(f);
}

static uint64_t render_and_hash(int32_t block) {
    bt_device_cfg dev;
    int line = 0;
    BT_CHECK_EQI(bt_device_cfg_load_file("golden_device.json", &dev, &line), BT_OK);

    bt_setlist *sl = NULL;
    BT_CHECK_EQI(bt_setlist_load_file("golden_setlist.json", &sl, &line), BT_OK);
    if (!sl) return 0;

    bt_song *song = &sl->song[0];
    BT_CHECK_EQI(bt_song_load_audio(song, sl->dir, SR), BT_OK);

    bt_engine_cfg ec = { SR, 4, 4096 };
    bt_engine *e = NULL;
    BT_CHECK_EQI(bt_engine_create(&ec, &e), BT_OK);
    BT_CHECK_EQI(bt_engine_set_song(e, song, &dev), BT_OK);

    bt_engine_seek(e, 0);
    bt_engine_play(e);

    bt_frame total = bt_song_length(song, SR);
    float *buf[4];
    for (int c = 0; c < 4; c++) buf[c] = (float *)calloc((size_t)total, sizeof(float));

    float *win[4];
    for (bt_frame pos = 0; pos < total; pos += block) {
        int32_t n = (int32_t)((total - pos < block) ? (total - pos) : block);
        for (int c = 0; c < 4; c++) win[c] = buf[c] + pos;
        bt_engine_render(e, win, n);
    }

    uint64_t h = bt_hash_init();
    for (int c = 0; c < 4; c++)
        h = bt_hash_bytes(h, buf[c], (size_t)total * sizeof(float));

    for (int c = 0; c < 4; c++) free(buf[c]);
    bt_engine_destroy(e);
    bt_setlist_free(sl);
    return h;
}

static void build_fixture(void) {
    write_stem("golden_a.wav", 11, 1, SR);        /* mono,   1 s */
    write_stem("golden_b.wav", 22, 2, SR / 2);    /* stereo, 0.5 s */

    write_text("golden_device.json",
        "{\"device\":\"offline\",\"sample_rate\":48000,\"buffer_frames\":512,"
        "\"buses\":[{\"name\":\"foh\",\"channels\":[0,1]},"
        "{\"name\":\"inear\",\"channels\":[2,3]}]}");

    write_text("golden_setlist.json",
        "{\"version\":1,\"name\":\"Golden\",\"songs\":[{"
        "\"title\":\"Golden\",\"tempo\":{\"bpm\":120,\"sig\":[4,4]},"
        "\"count_in_bars\":0,\"on_end\":\"stop\",\"tracks\":["
        "{\"name\":\"A\",\"type\":\"audio\",\"bus\":\"foh\","
        "\"file\":\"golden_a.wav\",\"gain_db\":0.0},"
        "{\"name\":\"B\",\"type\":\"audio\",\"bus\":\"inear\","
        "\"file\":\"golden_b.wav\",\"offset_ms\":120}"
        "]}]}");
}

static void cleanup(void) {
    remove("golden_a.wav");
    remove("golden_b.wav");
    remove("golden_device.json");
    remove("golden_setlist.json");
}

static void test_golden(void) {
    build_fixture();

    uint64_t h = render_and_hash(512);

    /* Block size must not change a single bit of the output. */
    BT_CHECK_EQI(render_and_hash(64),   (long long)h);
    BT_CHECK_EQI(render_and_hash(1024), (long long)h);
    BT_CHECK_EQI(render_and_hash(4096), (long long)h);

    if (GOLDEN_HASH == 0ULL) {
        fprintf(stderr, "  golden hash not pinned yet; observed 0x%016llxULL\n",
                (unsigned long long)h);
    } else {
        bt_checks++;
        if (h != GOLDEN_HASH) {
            bt_fails++;
            fprintf(stderr, "  FAIL golden render changed: got 0x%016llxULL, "
                            "expected 0x%016llxULL\n",
                    (unsigned long long)h, (unsigned long long)GOLDEN_HASH);
        }
    }
    cleanup();
}

int main(void) {
    BT_RUN(test_golden);
    BT_REPORT();
}
